/* ===== FIREBASE SYNC ===== */
function updateFbInd(c){document.querySelectorAll('.fb-badge').forEach(el=>{el.className='fb-badge '+(c?'on':'off');});document.getElementById('fbIndText').textContent=c?'雲端':'離線';document.querySelectorAll('.fbScanTxt,.fbPaperTxt,.fbRecTxt,.fbStudentTxt').forEach(t=>t.textContent=c?'雲端':'離線');}
function initFirebase(){if(typeof firebase==='undefined'){updateFbInd(false);return;}if(!firebase.firestore){updateFbInd(false);return;}try{if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG);db=firebase.firestore();fbConnected=true;updateFbInd(true);loadPapersFromFB();loadSettingsFromFB();loadStudentsFromFB();}catch(e){fbConnected=false;db=null;updateFbInd(false);toast('❌ Firebase 初始化失敗');}}
function showSyncBadge(t,c,d){const b=document.getElementById('syncBadge');b.textContent=t;b.className='sync-badge show '+c;setTimeout(()=>b.className='sync-badge',d||1500);}
function saveSettingsToFB(){if(!fbConnected||!db)return;showSyncBadge('☁️ 同步中...','saving');const data={G:{...G},go:groupOffsets.map(o=>({...o})),cr:cornerRatios,fm:fillMin,dt:darkThr,recs:records,HG:{...HG},headerColOffsets:JSON.parse(JSON.stringify(headerColOffsets)),years:YEARS,subjects:SUBJECTS,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};db.collection('omr_settings').doc('default').set(data).then(()=>showSyncBadge('✅ 已同步','saved')).catch(err=>showSyncBadge('❌ '+err.code,'error',3000));}
function loadSettingsFromFB(){if(!fbConnected||!db)return;db.collection('omr_settings').doc('default').get().then(doc=>{if(doc.exists){const d=doc.data();if(d.G)G={...G,...d.G};if(d.go){groupOffsets=d.go.map(o=>({dx:o.dx||0,dy:o.dy||0,drs:o.drs||0,dos:o.dos||0}));while(groupOffsets.length<16)groupOffsets.push({dx:0,dy:0,drs:0,dos:0});}if(d.cr)cornerRatios=d.cr;if(d.fm!==undefined)fillMin=d.fm;if(d.dt!==undefined)darkThr=d.dt;if(d.recs)records=d.recs;if(d.HG){if(d.HG.no1X!==undefined)HG.no1X=d.HG.no1X;if(d.HG.no2X!==undefined)HG.no2X=d.HG.no2X;if(d.HG.startY!==undefined)HG.startY=d.HG.startY;if(d.HG.rowS!==undefined)HG.rowS=d.HG.rowS;if(d.HG.hbw!==undefined)HG.hbw=d.HG.hbw;if(d.HG.hbh!==undefined)HG.hbh=d.HG.hbh;if(d.HG.enabled!==undefined)HG.enabled=d.HG.enabled;if(d.HG.clsX!==undefined)HG.clsX=d.HG.clsX;}if(d.headerColOffsets){['no1','no2','cls'].forEach(k=>{headerColOffsets[k]=d.headerColOffsets[k]?{dx:d.headerColOffsets[k].dx||0,dy:d.headerColOffsets[k].dy||0}:{dx:0,dy:0};});}if(d.years&&Array.isArray(d.years)){d.years.forEach(y=>{if(!YEARS.includes(y))YEARS.push(y);});YEARS.sort();}if(d.subjects&&Array.isArray(d.subjects)){d.subjects.forEach(s=>{if(!SUBJECTS.includes(s)){const idx=SUBJECTS.indexOf('其他');if(idx>=0)SUBJECTS.splice(idx,0,s);else SUBJECTS.push(s);}});}buildGrpSel();updGrpDisp();syncDetSliders();syncHeaderSliders();updHdrColDisp();refreshYearDropdowns();fillSubjectSelect();renderRecTabs();saveToLS();}}).catch(()=>{});}
function debouncedFbSave(){if(!fbConnected)return;clearTimeout(fbSaveTimer);fbSaveTimer=setTimeout(saveSettingsToFB,1500);}
function saveStudentsToDB(){saveToLS();if(!fbConnected||!db)return;showSyncBadge('☁️ 儲存學生...','saving');db.collection('student_data').doc('default').set({data:studentDB,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}).then(()=>showSyncBadge('✅ 已同步','saved')).catch(err=>showSyncBadge('❌ '+err.code,'error',3000));}
function loadStudentsFromFB(){if(!fbConnected||!db)return;db.collection('student_data').doc('default').get().then(doc=>{if(doc.exists&&doc.data().data){studentDB=doc.data().data;renderStudentList();saveToLS();}}).catch(()=>{});}
function savePaperToFB(paper,cb){if(!fbConnected||!db){if(cb)cb();return;}showSyncBadge('☁️ 儲存試卷...','saving');const data={...paper,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};delete data.id;const ref=paper.id&&!paper.id.startsWith('local_')?db.collection('papers').doc(paper.id):db.collection('papers').doc();const docId=paper.id&&!paper.id.startsWith('local_')?paper.id:ref.id;ref.set(data).then(()=>{paper.id=docId;showSyncBadge('✅ 已儲存','saved');if(cb)cb();}).catch(err=>{showSyncBadge('❌ '+err.code,'error',3000);if(cb)cb();});}
function deletePaperFromFB(id,cb){if(!fbConnected||!db){if(cb)cb();return;}db.collection('papers').doc(id).delete().then(()=>{showSyncBadge('✅ 已刪除','saved');if(cb)cb();}).catch(err=>{showSyncBadge('❌ '+err.code,'error',3000);if(cb)cb();});}
function loadPapersFromFB(){if(!fbConnected||!db){toast('⚠️ 未連接雲端');return;}showSyncBadge('☁️ 載入試卷...','saving');db.collection('papers').orderBy('year','desc').get().then(snap=>{papers=[];snap.forEach(doc=>{const d=doc.data();d.id=doc.id;papers.push(d);});renderPaperTabs();renderPaperSelectList();populateSubjectFilter();saveToLS();showSyncBadge('✅ 已載入 '+papers.length+' 份','saved');}).catch(err=>showSyncBadge('❌ '+err.code,'error',3000));}