/* ===== HEADER BUBBLE (CLASS NUMBER + ELECTIVE SCAN CLASS) DETECTION ===== */
function resetHeaderAutoOffsets(){headerAutoOffsets={no1:{dx:0,dy:0},no2:{dx:0,dy:0},cls:{dx:0,dy:0}};}
function getHeaderBubblePos(col,row,useAutoOffset){const colOff=headerColOffsets[col]||{dx:0,dy:0};const autoOff=useAutoOffset?(headerAutoOffsets[col]||{dx:0,dy:0}):{dx:0,dy:0};let x;switch(col){case'no1':x=HG.no1X;break;case'no2':x=HG.no2X;break;case'cls':x=HG.clsX;break;default:x=0;}return{x:x+colOff.dx+autoOff.dx,y:HG.startY+row*HG.rowS+colOff.dy+autoOff.dy};}
function getHdrFillRatio(gray,cx,cy,thr){const hw=Math.floor(HG.hbw/2),hh=Math.floor(HG.hbh/2);let dark=0,cnt=0;const icx=Math.round(cx),icy=Math.round(cy);for(let dy=-hh;dy<=hh;dy++)for(let dx=-hw;dx<=hw;dx++){const px=icx+dx,py=icy+dy;if(px>=0&&px<CW&&py>=0&&py<CH){cnt++;if(gray[py*CW+px]<thr)dark++;}}return cnt>0?dark/cnt:0;}
/* 啟用選修科時，連同「掃描班別」欄一併自動對齊 */
function autoAlignHeader(gray,otsuVal){if(!HG.enabled)return;const thr=darkThr>0?darkThr:otsuVal;const cols=electiveScanMode?['cls','no1','no2']:['no1','no2'];cols.forEach(key=>{autoAlignOneHeaderCol(key,HDR_COL_COUNTS[key],gray,thr);});}
function autoAlignOneHeaderCol(colKey,count,gray,thr){const hw=Math.floor(HG.hbw/2),hh=Math.floor(HG.hbh/2);const basePts=[];for(let r=0;r<count;r++)basePts.push(getHeaderBubblePos(colKey,r,false));function scoreOffset(dx,dy){const ratios=[];for(const bp of basePts){const cx=Math.round(bp.x+dx),cy=Math.round(bp.y+dy);let dark=0,cnt=0;for(let iy=-hh;iy<=hh;iy++){const py=cy+iy;if(py<0||py>=CH)continue;const ro=py*CW;for(let ix=-hw;ix<=hw;ix++){const px=cx+ix;if(px>=0&&px<CW){cnt++;if(gray[ro+px]<thr)dark++;}}}ratios.push(cnt>0?dark/cnt:0);}const mean=ratios.reduce((a,v)=>a+v,0)/ratios.length;return ratios.reduce((a,v)=>a+(v-mean)*(v-mean),0)/ratios.length;}let bestS=-1,bestDx=0,bestDy=0;for(let dx=-12;dx<=12;dx+=2)for(let dy=-12;dy<=12;dy+=2){const s=scoreOffset(dx,dy);if(s>bestS){bestS=s;bestDx=dx;bestDy=dy;}}let fDx=bestDx,fDy=bestDy,fS=bestS;for(let dx=bestDx-2.5;dx<=bestDx+2.5;dx+=.5)for(let dy=bestDy-2.5;dy<=bestDy+2.5;dy+=.5){const s=scoreOffset(dx,dy);if(s>fS){fS=s;fDx=dx;fDy=dy;}}headerAutoOffsets[colKey]={dx:fDx,dy:fDy};}
function applyHdrAutoToPersistent(){const keys=electiveScanMode?['cls','no1','no2']:['no1','no2'];keys.forEach(key=>{headerColOffsets[key].dx+=(headerAutoOffsets[key]||{dx:0}).dx;headerColOffsets[key].dy+=(headerAutoOffsets[key]||{dy:0}).dy;headerAutoOffsets[key]={dx:0,dy:0};});}
function selHdrCol(col){selectedHdrCol=col;document.getElementById('hdrColSel').value=col;updHdrColDisp();drawGrid();}
function updHdrColDisp(){const off=headerColOffsets[selectedHdrCol]||{dx:0,dy:0};document.getElementById('hdrColDxV').textContent=(off.dx||0).toFixed(1);document.getElementById('hdrColDyV').textContent=(off.dy||0).toFixed(1);}
function nudgeHdrCol(axis,dir){const step=+(document.getElementById('hdrStepSz').value)||1;if(!headerColOffsets[selectedHdrCol])headerColOffsets[selectedHdrCol]={dx:0,dy:0};headerColOffsets[selectedHdrCol][axis]=(headerColOffsets[selectedHdrCol][axis]||0)+dir*step;updHdrColDisp();drawGrid();saveSettings();}
function resetHdrCol(){headerColOffsets[selectedHdrCol]={dx:0,dy:0};updHdrColDisp();drawGrid();saveSettings();}
function resetAllHdrCols(){['no1','no2','cls'].forEach(k=>headerColOffsets[k]={dx:0,dy:0});updHdrColDisp();drawGrid();saveSettings();}
function autoAlignSelectedHdrCol(){if(!corrGray){showMsg('請先完成步驟 2');return;}const thr=darkThr>0?darkThr:computedOtsu;autoAlignOneHeaderCol(selectedHdrCol,HDR_COL_COUNTS[selectedHdrCol],corrGray,thr);headerColOffsets[selectedHdrCol].dx+=(headerAutoOffsets[selectedHdrCol]||{dx:0}).dx;headerColOffsets[selectedHdrCol].dy+=(headerAutoOffsets[selectedHdrCol]||{dy:0}).dy;headerAutoOffsets[selectedHdrCol]={dx:0,dy:0};updHdrColDisp();drawGrid();saveSettings();toast(`✅ ${selectedHdrCol} 欄已對齊`);}
function autoAlignAllHdrCols(){if(!corrGray){showMsg('請先完成步驟 2');return;}autoAlignHeader(corrGray,computedOtsu);applyHdrAutoToPersistent();updHdrColDisp();drawGrid();saveSettings();toast('✅ 班號欄已對齊');}
function readHeaderBubbles(gray,otsuVal){if(!HG.enabled)return null;const thr=darkThr>0?darkThr:otsuVal,fmin=fillMin/100;function readCol(col,count){const ratios=[];for(let r=0;r<count;r++){const p=getHeaderBubblePos(col,r,true);ratios.push(getHdrFillRatio(gray,p.x,p.y,thr));}return ratios;}function findBest(ratios){const filled=[];for(let i=0;i<ratios.length;i++)if(ratios[i]>=fmin)filled.push(i);if(filled.length===1)return filled[0];if(filled.length>1){let best=-1,bestR=0;filled.forEach(i=>{if(ratios[i]>bestR){bestR=ratios[i];best=i;}});return best;}return null;}const no1R=readCol('no1',10),no2R=readCol('no2',10);const no1Idx=findBest(no1R),no2Idx=findBest(no2R);const number=(no1Idx!==null&&no2Idx!==null)?no1Idx*10+no2Idx:null;let classLetter=null,clsR=null;if(electiveScanMode){clsR=readCol('cls',9);const ci=findBest(clsR);classLetter=ci!==null?ELEC_CLASS_LETTERS[ci]:null;}return{number,classLetter,no1Ratios:no1R,no2Ratios:no2R,clsRatios:clsR,matchedStudent:null};}
function readHeaderBubblesFrom(gray,otsuVal){if(!HG.enabled)return null;const thr=darkThr>0?darkThr:otsuVal,fmin=fillMin/100;function readCol(col,count){const ratios=[];for(let r=0;r<count;r++){const p=getHeaderBubblePos(col,r,true);ratios.push(getHdrFillRatio(gray,p.x,p.y,thr));}return ratios;}function findBest(ratios){const filled=[];for(let i=0;i<ratios.length;i++)if(ratios[i]>=fmin)filled.push(i);if(filled.length===1)return filled[0];if(filled.length>1){let best=-1,bestR=0;filled.forEach(i=>{if(ratios[i]>bestR){bestR=ratios[i];best=i;}});return best;}return null;}const no1R=readCol('no1',10),no2R=readCol('no2',10);const no1Idx=findBest(no1R),no2Idx=findBest(no2R);const number=(no1Idx!==null&&no2Idx!==null)?no1Idx*10+no2Idx:null;let classLetter=null,clsR=null;if(electiveScanMode){clsR=readCol('cls',9);const ci=findBest(clsR);classLetter=ci!==null?ELEC_CLASS_LETTERS[ci]:null;}return{number,classLetter,no1Ratios:no1R,no2Ratios:no2R,clsRatios:clsR,matchedStudent:null};}
/* 偵測學生：
   一般班別 → 以班號對應該班學生；
   選修科班別 → 以「級別數字 + 掃描班別字母」對應 origClass，再以班號對應 origNumber。 */
function autoDetectStudent(hdrInfo){if(!hdrInfo)return null;if(!selectedScanClass)return null;const year=getYearFromPaper();if(!year)return null;const students=(studentDB[year]||[]).filter(s=>s.class===selectedScanClass);if(electiveScanMode){if(!hdrInfo.classLetter||hdrInfo.number===null||hdrInfo.number===0)return null;const gradeNum=getGradeNumFromPaper();if(!gradeNum)return null;const fullClass=gradeNum+hdrInfo.classLetter;return students.find(s=>s.origClass===fullClass&&(s.origNumber||0)===hdrInfo.number)||null;}if(hdrInfo.number===null||hdrInfo.number===0)return null;return students.find(s=>s.number===hdrInfo.number)||null;}
function applyHeaderDetection(){if(!detectedHeaderInfo)return;const student=autoDetectStudent(detectedHeaderInfo);detectedHeaderInfo.matchedStudent=student;if(student){setTimeout(()=>{populateStudentDropdown();document.getElementById('studentSelect').value=student.name;document.getElementById('studentName').value=student.name;if(batchMode&&batchResults[currentBatchIdx])batchResults[currentBatchIdx].studentName=student.name;},50);}}
function renderHeaderDetectUI(){const bar=document.getElementById('headerDetectBar');const note=document.getElementById('hdrOverrideNote');if(!detectedHeaderInfo||!HG.enabled){bar.classList.add('hidden');note.classList.add('hidden');return;}bar.classList.remove('hidden');const h2=detectedHeaderInfo,stu=h2.matchedStudent;const numOk=h2.number!==null&&h2.number>0;const clsOk=!electiveScanMode||!!h2.classLetter;const allOk=numOk&&clsOk&&stu;let cls2='hdr-bar '+(allOk?'hdr-found':((numOk&&clsOk)?'hdr-partial':'hdr-none'));let html=allOk?'🎯 學生自動偵測成功 ':'⚠️ 班號偵測 ';if(electiveScanMode){if(h2.classLetter)html+=`<span class="hdr-chip hdr-chip-ok">掃描班別 ${h2.classLetter}</span>`;else html+=`<span class="hdr-chip hdr-chip-warn">掃描班別 ？</span>`;}if(numOk)html+=`<span class="hdr-chip hdr-chip-ok">班號 ${h2.number}</span>`;else html+=`<span class="hdr-chip hdr-chip-warn">班號 ？</span>`;if(electiveScanMode&&h2.classLetter&&numOk){const gn=getGradeNumFromPaper();if(gn)html+=`<span class="hdr-chip hdr-chip-info">→ ${gn}${h2.classLetter} #${h2.number}</span>`;}else if(selectedScanClass)html+=`<span class="hdr-chip hdr-chip-info">→ ${selectedScanClass} 班</span>`;const aoKeys=electiveScanMode?['cls','no1','no2']:['no1','no2'];const aoAny=aoKeys.some(k=>{const o=headerAutoOffsets[k];return o&&(Math.abs(o.dx)>0.1||Math.abs(o.dy)>0.1);});if(aoAny)html+=`<span class="hdr-auto-tag">⚡ 已自動校準</span>`;bar.className=cls2;bar.innerHTML=html;if(stu){const metaCls=electiveScanMode?(stu.origClass||''):selectedScanClass;const metaNum=electiveScanMode?(stu.origNumber!=null?stu.origNumber:stu.number):stu.number;bar.innerHTML+=`<div class="hdr-stu-match" style="width:100%;margin-top:6px"><div style="font-size:1.5em">👤</div><div><div class="hsm-name">${stu.name}</div><div class="hsm-meta">${metaCls} 班 · 學號 ${metaNum}${electiveScanMode?' · 選修：'+selectedScanClass:''}</div></div></div>`;note.classList.remove('hidden');}else{if(electiveScanMode&&!h2.classLetter)bar.innerHTML+=`<div style="width:100%;font-size:.76em;color:rgb(var(--amber));margin-top:4px">⚠️ 未能偵測掃描班別，請確認已塗滿班別欄（A–S）</div>`;else if(numOk&&selectedScanClass){const gn=getGradeNumFromPaper();const tip=electiveScanMode&&h2.classLetter&&gn?`${gn}${h2.classLetter} 班 學號 ${h2.number}`:`${selectedScanClass} 班 學號 ${h2.number}`;bar.innerHTML+=`<div style="width:100%;font-size:.76em;color:rgb(var(--amber));margin-top:4px">⚠️ 在學生資料庫中找不到 ${tip}</div>`;}else if(numOk&&!selectedScanClass)bar.innerHTML+=`<div style="width:100%;font-size:.76em;color:rgb(var(--amber));margin-top:4px">⚠️ 請先選擇班別以匹配學生</div>`;note.classList.add('hidden');}}
function syncHeaderSliders(){document.getElementById('sHN1').value=HG.no1X;document.getElementById('sHN2').value=HG.no2X;document.getElementById('sHSY').value=HG.startY;document.getElementById('sHRS').value=HG.rowS;document.getElementById('sHBW').value=HG.hbw;document.getElementById('sHBH').value=HG.hbh;document.getElementById('hdrEnabled').checked=HG.enabled;updHeaderSliderVals();}
function updHeaderSliderVals(){document.getElementById('vHN1').textContent=HG.no1X;document.getElementById('vHN2').textContent=HG.no2X;document.getElementById('vHSY').textContent=HG.startY;document.getElementById('vHRS').textContent=HG.rowS;document.getElementById('vHBW').textContent=HG.hbw;document.getElementById('vHBH').textContent=HG.hbh;}
function onHeaderSlider(){HG.no1X=+document.getElementById('sHN1').value;HG.no2X=+document.getElementById('sHN2').value;HG.startY=+document.getElementById('sHSY').value;HG.rowS=+document.getElementById('sHRS').value;HG.hbw=+document.getElementById('sHBW').value;HG.hbh=+document.getElementById('sHBH').value;updHeaderSliderVals();drawGrid();saveSettings();}
function resetHeaderDefaults(){HG={no1X:288,no2X:324,startY:167,rowS:27.5,hbw:14,hbh:10,enabled:true,clsX:252};headerColOffsets={no1:{dx:0,dy:0},no2:{dx:0,dy:0},cls:{dx:0,dy:0}};syncHeaderSliders();updHdrColDisp();drawGrid();saveSettings();}
function testHeaderRead(){if(!corrGray){showMsg('請先完成步驟 2（四角定位）');return;}resetHeaderAutoOffsets();autoAlignHeader(corrGray,computedOtsu);const info=readHeaderBubbles(corrGray,computedOtsu);const box=document.getElementById('headerTestResult');box.classList.remove('hidden');if(!info){box.className='status s-err';box.innerHTML='偵測已停用';return;}const stu=autoDetectStudent(info);let html='<strong>偵測結果：</strong><br>';if(electiveScanMode&&info.clsRatios){html+=`掃描班別：${info.classLetter||'？'} [${info.clsRatios.map(r=>Math.round(r*100)+'%').join(', ')}]<br>`;}html+=`班號十位：${info.no1Ratios?findMaxIdx(info.no1Ratios):'?'} [${info.no1Ratios.map(r=>Math.round(r*100)+'%').join(', ')}]<br>`;html+=`班號個位：${info.no2Ratios?findMaxIdx(info.no2Ratios):'?'} [${info.no2Ratios.map(r=>Math.round(r*100)+'%').join(', ')}]<br>`;html+=`→ 班號：<strong>${info.number!==null?info.number:'？'}</strong>`;if(electiveScanMode&&info.classLetter&&info.number){const gn=getGradeNumFromPaper();if(gn)html+=` · 對應原班：<strong>${gn}${info.classLetter} #${info.number}</strong>`;}if(selectedScanClass)html+=` · 班別：<strong>${selectedScanClass}</strong>`;if(stu)html+=`<br>✅ 匹配學生：<strong>${stu.name}</strong>`;else if(info.number&&selectedScanClass)html+=`<br>⚠️ 未能匹配學生`;else if(info.number&&!selectedScanClass)html+=`<br>⚠️ 請先選擇班別`;const aoKeys=electiveScanMode?['cls','no1','no2']:['no1','no2'];const aoStr=aoKeys.map(k=>{const o=headerAutoOffsets[k];return`${k}(${o.dx.toFixed(1)},${o.dy.toFixed(1)})`;}).join(' ');html+=`<br><span style="font-size:.72em;color:var(--text3)">⚡ 自動校準偏移：${aoStr}</span>`;box.className='status '+(stu?'s-ok':'s-info');box.innerHTML=html;}
function findMaxIdx(arr){let mx=-1,mi=-1;arr.forEach((v,i)=>{if(v>mx){mx=v;mi=i;}});return mi>=0?mi+'('+Math.round(mx*100)+'%)':'?';}
function startHeaderCalib(){hdrCalibActive=true;hdrCalibStep=0;hdrCalibPts=[];document.getElementById('calibStatus').innerHTML=`🔢 班號校準 [1/3]：點擊 <strong>${HDR_CALIB_LABELS[0]}</strong>`;document.getElementById('calibStatus').style.cssText='background:rgba(34,211,238,.08);border-color:rgba(34,211,238,.15);color:rgb(34,211,238)';drawGrid();}
function handleHeaderCalibClick(cx,cy){hdrCalibPts.push({x:cx,y:cy});hdrCalibStep++;if(hdrCalibStep<3){document.getElementById('calibStatus').innerHTML=`🔢 班號校準 [${hdrCalibStep+1}/3]：點擊 <strong>${HDR_CALIB_LABELS[hdrCalibStep]}</strong>`;}else finishHeaderCalib();drawGrid();}
function finishHeaderCalib(){hdrCalibActive=false;const[p1,p2,p3]=hdrCalibPts;HG.no1X=p1.x;HG.startY=p1.y;const dy=p2.y-p1.y;if(dy>1)HG.rowS=dy/9;HG.no2X=p3.x;/* 自動把掃描班別欄放到班號十位左方（與十位、個位等距） */HG.clsX=HG.no1X-(HG.no2X-HG.no1X);resetAllHdrCols();syncHeaderSliders();drawGrid();saveSettings();document.getElementById('calibStatus').innerHTML='✅ 班號校準完成！';document.getElementById('calibStatus').style.cssText='background:rgba(52,211,153,.08);border-color:rgba(52,211,153,.15);color:rgb(52,211,153)';}
/* 依目前是否為選修科模式，重建「各欄獨立微調」下拉選單（含掃描班別） */
function updateHdrColSelOptions(){const sel=document.getElementById('hdrColSel');if(!sel)return;const cur=selectedHdrCol;let opts='';if(electiveScanMode)opts+='<option value="cls">掃描班別 (A–S)</option>';opts+='<option value="no1">班號十位</option><option value="no2">班號個位</option>';sel.innerHTML=opts;const valid=[...sel.options].some(o=>o.value===cur);if(electiveScanMode&&!valid)selectedHdrCol='cls';else if(!valid)selectedHdrCol='no1';sel.value=selectedHdrCol;updHdrColDisp();}