/* ===== NAVIGATION / STEPS / MODAL / TOAST ===== */
function navigateTo(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('page-active'));const el=document.getElementById(id);if(el){el.classList.add('page-active');window.scrollTo({top:0});}if(id==='recordPage')renderRecTabs();if(id==='paperPage')renderPaperTabs();if(id==='studentPage')renderStudentList();if(id==='scanPage')renderPaperSelectList();}
function goHome(){navigateTo('landingPage');}
function buildStepProgress(){const box=document.getElementById('stepProgress');box.innerHTML='';STEP_LABELS.forEach((lbl,i)=>{if(i>0){const ln=document.createElement('div');ln.className='step-line';ln.id='stepLine'+i;box.appendChild(ln);}const it=document.createElement('div');it.className='step-item'+(i===0?' active':'');it.id='stepItem'+i;it.onclick=()=>{if(i<=maxReachedStep)showScanStep(i);};it.innerHTML=`<div class="step-circle">${i+1}</div><div class="step-lbl">${lbl}</div>`;box.appendChild(it);});}
function updateStepProgress(){for(let i=0;i<STEP_LABELS.length;i++){const it=document.getElementById('stepItem'+i);if(!it)continue;it.classList.remove('active','done');if(i===currentScanStep)it.classList.add('active');else if(i<currentScanStep)it.classList.add('done');it.querySelector('.step-circle').textContent=i<currentScanStep?'✓':i+1;}for(let i=1;i<STEP_LABELS.length;i++){const ln=document.getElementById('stepLine'+i);if(ln)ln.classList.toggle('done',i<=currentScanStep);}}
function showScanStep(n){currentScanStep=n;if(n>maxReachedStep)maxReachedStep=n;document.querySelectorAll('.scan-step').forEach(s=>s.classList.remove('step-active'));const el=document.getElementById('scanStep'+n);if(el)el.classList.add('step-active');updateStepProgress();if(n===2&&srcImg)drawCorners();if(n===3&&corrCanvas){drawGrid();updateBatchBtn();}if(n===4)populateStudentDropdown();window.scrollTo({top:0,behavior:'smooth'});}
function proceedFromStep0(){if(!selectedPaperId){showMsg('⚠️ 請先選擇試卷再繼續。');return;}const year=getYearFromPaper();const hasStudents=year&&(studentDB[year]||[]).length>0;if(!selectedScanClass){if(!hasStudents){showMsg(`⚠️ 學年 <strong>${year||''}</strong> 尚未匯入學生資料。<br>請先到「學生管理」匯入學生，並在此選擇班別後才能繼續。`);}else{showMsg('⚠️ 請先選擇班別才能進行下一步。<br>選擇班別後，系統才能自動偵測答題卡上的班號並匹配學生。');}return;}showScanStep(1);}

/* ===== DROPDOWN POPULATION (YEAR / GRADE / SUBJECT) ===== */
function fillYearSelect(sel){if(!sel)return;const cur=sel.value&&sel.value!=='__add__'?sel.value:'';sel.innerHTML='';YEARS.forEach(y=>{const o=document.createElement('option');o.value=y;o.textContent=y;sel.appendChild(o);});const a=document.createElement('option');a.value='__add__';a.textContent='➕ 新增學年…';sel.appendChild(a);if(cur&&YEARS.includes(cur))sel.value=cur;else sel.value=YEARS[0]||'';sel.dataset.prev=sel.value;}
function refreshYearDropdowns(){['pYear','stuManYear'].forEach(id=>fillYearSelect(document.getElementById(id)));}
function fillSubjectSelect(){const sel=document.getElementById('pSubject');if(!sel)return;const cur=sel.value&&sel.value!=='__add__'?sel.value:'';sel.innerHTML='';SUBJECTS.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o);});const a=document.createElement('option');a.value='__add__';a.textContent='➕ 新增科目…';sel.appendChild(a);if(cur&&SUBJECTS.includes(cur))sel.value=cur;else sel.value=SUBJECTS[0]||'';sel.dataset.prev=sel.value;}
function onYearSelectChange(sel){if(sel.value==='__add__'){addCustomYear(sel.id,sel.dataset.prev||'');}else{sel.dataset.prev=sel.value;}}
function onSubjectSelectChange(sel){if(sel.value==='__add__'){addCustomSubject(sel.dataset.prev||'');}else{sel.dataset.prev=sel.value;}}
function addCustomYear(targetId,prevVal){showPrompt('🗓️ 新增學年<br><span style="font-size:.72em;color:var(--text3)">建議格式：2029/2030</span>','例如 2029/2030',function(v){if(!YEARS.includes(v)){YEARS.push(v);YEARS.sort();}refreshYearDropdowns();const sel=document.getElementById(targetId);if(sel){sel.value=v;sel.dataset.prev=v;}saveSettings();toast('✅ 已新增學年 '+v);},function(){const sel=document.getElementById(targetId);if(sel){sel.value=prevVal||(YEARS[0]||'');sel.dataset.prev=sel.value;}});}
function addCustomSubject(prevVal){showPrompt('📚 新增科目','例如 視覺藝術',function(v){ensureSubjectOption(v);const sel=document.getElementById('pSubject');if(sel){sel.value=v;sel.dataset.prev=v;}saveSettings();toast('✅ 已新增科目 '+v);},function(){const sel=document.getElementById('pSubject');if(sel){sel.value=prevVal||(SUBJECTS[0]||'');sel.dataset.prev=sel.value;}});}
function ensureYearOption(y){if(y&&!YEARS.includes(y)){YEARS.push(y);YEARS.sort();refreshYearDropdowns();}}
function ensureSubjectOption(s){if(s&&!SUBJECTS.includes(s)){const idx=SUBJECTS.indexOf('其他');if(idx>=0)SUBJECTS.splice(idx,0,s);else SUBJECTS.push(s);fillSubjectSelect();}}

function populateDropdowns(){refreshYearDropdowns();const pg=document.getElementById('pGrade');if(pg){const cur=pg.value;pg.innerHTML='';GRADES.forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=g;pg.appendChild(o);});if(cur)pg.value=cur;}updatePaperTermOptions();updateDisplayNameRow();fillSubjectSelect();populateSubjectFilter();}
function populateSubjectFilter(){const sel=document.getElementById('filterSubject');if(!sel)return;const cur=sel.value;const subjects=[...new Set(papers.map(p=>p.subject).filter(Boolean))].sort();sel.innerHTML='<option value="">全部科目</option>';subjects.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;sel.appendChild(o);});sel.value=cur;}
function showMsg(s){document.getElementById('modalMsg').innerHTML=s;document.getElementById('modalBtns').innerHTML='<button class="btn btn-p" onclick="closeModal()">確定</button>';document.getElementById('modal').classList.add('show');}
function showConfirm(msg,onYes){document.getElementById('modalMsg').innerHTML=msg;document.getElementById('modalBtns').innerHTML='<button class="btn btn-danger" id="modalYes">確認</button><button class="btn btn-s" onclick="closeModal()">取消</button>';document.getElementById('modal').classList.add('show');document.getElementById('modalYes').onclick=()=>{closeModal();onYes();};}
function showPrompt(msg,placeholder,onConfirm,onCancel){document.getElementById('modalMsg').innerHTML=msg+`<input id="promptInput" class="text-input" style="width:100%;margin-top:14px" placeholder="${placeholder||''}">`;document.getElementById('modalBtns').innerHTML='<button class="btn btn-p" id="promptOkBtn">確定</button><button class="btn btn-s" id="promptCancelBtn">取消</button>';document.getElementById('modal').classList.add('show');const inp=document.getElementById('promptInput');setTimeout(()=>{if(inp)inp.focus();},60);const ok=()=>{const v=inp.value.trim();closeModal();if(v){onConfirm(v);}else if(onCancel){onCancel();}};document.getElementById('promptOkBtn').onclick=ok;document.getElementById('promptCancelBtn').onclick=()=>{closeModal();if(onCancel)onCancel();};if(inp)inp.onkeydown=(e)=>{if(e.key==='Enter'){e.preventDefault();ok();}};}
function closeModal(){document.getElementById('modal').classList.remove('show');}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500);}
function getGradeDisplay(p){return p.grade||p.className||'—';}
function paperLabel(p){let l=`${p.year} · ${getGradeDisplay(p)} · ${p.term}`;if(p.set)l+=` · ${p.set}`;l+=` · ${p.subject||''} (${p.totalQ}題)`;return l;}
function updatePaperBar(){const bar=document.getElementById('paperBarScan');if(selectedPaperId){const p=papers.find(x=>x.id===selectedPaperId);let txt=p?paperLabel(p):'—';if(selectedScanClass)txt+=` · ${selectedScanClass}`;bar.className='paper-bar has-paper';bar.innerHTML=`✅ <strong>${txt}</strong>`;}else{bar.className='paper-bar';bar.innerHTML='📋 尚未選擇試卷';}}

/* 有填顯示名稱就用顯示名稱，否則用學期 */
function getPaperTermDisplay(p){return (p&&p.displayName&&String(p.displayName).trim())?String(p.displayName).trim():(p?p.term||'':'');}
function paperLabel(p){let l=`${p.year} · ${getGradeDisplay(p)} · ${getPaperTermDisplay(p)}`;if(p.set)l+=` · ${p.set}`;l+=` · ${p.subject||''} (${p.totalQ}題)`;return l;}
